inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.7

Layout/EmptyLinesAroundClassBody:
    EnforcedStyle: beginning_only

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true
    # AllowAliasSyntax: true

Layout/ExtraSpacing:
    AllowForAlignment: false

Layout/SpaceAroundMethodCallOperator:
    Enabled: true

Layout/SpaceAroundOperators:
    AllowForAlignment: false
    
Lint/DeprecatedOpenSSLConstant:
    Enabled: true

Lint/RaiseException:
    Enabled: true
    
Lint/StructNewOverride:
    Enabled: true
    
Style/Documentation:
    Enabled: false

Style/ExponentialNotation:
    Enabled: true
    
Style/FrozenStringLiteralComment:
    Enabled: false

Style/HashEachMethods:
    Enabled: true
    
Style/HashTransformKeys:
    Enabled: true
    
Style/HashTransformValues:
    Enabled: true
    
Style/SlicingWithRange:
    Enabled: true
    