version: '3.4'
x-app:
  &app
  build:
    context: .
    target: app
  expose:
    - "22"
x-db:
  &db
  image: "mysql/mysql-server:5.7.30"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: deadpool
    MYSQL_USER: deadpool
    MYSQL_PASSWORD: password
  
services:
  monitor:
    build:
      context: .
      target: monitor
    entrypoint: ["/opt/docker/init-deadpool.sh"]
  app1: *app
  app2: *app
  db1: *db
  db2: *db
